#!/bin/bash
#SBATCH --partition=genoa
#SBATCH --ntasks=192
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=192
#SBATCH --time=58:00:00


module load 2023
module load foss/2023a
module load netCDF-Fortran/4.6.1-gompi-2023a
module load CMake/3.26.3-GCCcore-12.3.0
# module load Hypre/2.25.0-foss-2022a # optional

DALES=/home/jansson/dales-tester/build-6dde0-sp-genoa-gnu-fast/src/dales4.4

srun $DALES namoptions.001 | tee -a output.txt
